services:
  php:
    build: docker/php8.0
    container_name: culturefeed-php
    working_dir: /cdb
    volumes:
      - .:/cdb
    stdin_open: true
    tty: true
    command: php -a

volumes:
  cdb:
    driver: local